### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by zivester**
Keep everything as promises

@mbernardy @chevett

### CODE REVIEW

**Comment by chevett** [comment]
add version bump?

**Comment by zivester** [comment]
Merged.  I bumped it after merge.  I don't have permissions to publish this module for some reason... I'll update the link in the other PR if you can publish 1.1.0

**Comment by chevett** [comment]
Right I'll publish it.  I think I published it under chevett

**Comment by chevett** [comment]
published 1.1.0

**Pull request merged**
